# Generated by Django 2.0 on 2018-11-08 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='permission',
            field=models.CharField(choices=[('1', 'Worker'), ('2', 'Admin')], default=1, max_length=1, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1)]),
        ),
    ]
